### ISSUE TITLE
Add relevant comments in source code

### ISSUE THREAD

**Issue by ashutosh97** [lugnitdgp/Learn-Python#1]

**Comment by devonJS** [comment]
hi, I can help you with this.  I like to teach others coding basics and provide easy-to-understand explanations to what code is doing.  Were you looking for just explanations to what your code is doing?

**Comment by ashutosh97** [comment]
Yes, line wise explanations with the help of comments will be helpful.

**Comment by devonJS** [comment]
cool, i'll tackle what you have so far later today.

**Comment by Danushka96** [comment]
I forked and commented Here is the link: https://github.com/Danushka96/Learn-Python

**Comment by Danushka96** [comment]
Ok thanks I'll check them

**Comment by devonJS** [comment]
i will add to which ever files @Danushka96 does not get to.

**Comment by TheGunder** [comment]
Hello, I would like to help with this.  Do you have a list of other examples you would like to be written?  Are we okay to just come up with some and submit them, or would you just like help commenting the examples you have already created?  I started working on an example for recursion and then thought I should clarify with you first.

**Comment by devonJS** [comment]
@TheGunder issue #2 covers new examples

**Comment by TheGunder** [comment]
Yep I see that now.  Sorry I missed that,
