### ISSUE TITLE
Add new codes.

### ISSUE THREAD

**Issue by modihere** [lugnitdgp/Learn-Python#2]
Ask People to add more python basic codes to this repo.
Tag this as Hacktoberfest also.

**Comment by ashutosh97** [comment]
Yes, that will be helpful.

**Comment by ew4321** [comment]
I can work on this when I get out of class in 2+ hours.

**Comment by iyanuashiri** [comment]
This repo makes use of Python 2?

**Comment by ew4321** [comment]
Looks like it.

**Comment by TheGunder** [comment]
Will it be an issue if what I'm working on is for Python 3?  Should I just put a comment in the code?

**Comment by modihere** [comment]
Yes, put up a comment at the start of the program that python3 should be used.

**Comment by delanou** [comment]
Can I get permission to add examples?

**Comment by WTFox** [comment]
Added a sample for python generators.
